/**
 * 
 */
/**
 * 
 * NOME DA DEMANDA: SPRINT 1
 * FLUXO: PEDIDO + DEVOLUÇÃO
 * APLICAÇÕES DO CONTEXTO: VA + PDV + SAP
 * 
 * CONTEXTO DE NEGÓCIO PRINCIPAL: 
 * 
 * - NOTA FISCAL CUPONADA 
 * - PEDIDOS GERADOS COM FLUXO SAÍDA: CAIXA, RETIRADA INTERNA IMEDIA E EXTERNA IMEDIATA
 * - FORMA DE PAGAMENTO : DINHEIRO
 * - TIPO DE DEVOLUÇÃO: VALE TROCA
 * 
 * @author Softtek - QA
 *
 */
package br.lry.qa.rsp.pjttrc.frt001.rgr.va.rgr00001;